name: Android Release CI with Flavor & Signing

on:
  push:
    branches: ["modular/dev"]
  pull_request:
    branches: ["modular/dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: [staging]

    steps:
      - name: üîÑ Checkout Repository
        uses: actions/checkout@v4

      - name: üõ†Ô∏è Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: üì¶ Install melos + bootstrap
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: üîç Flutter version
        run: flutter --version

      - name: ‚úÖ Run tests
        run: melos run test

      - name: üóùÔ∏è Decode keystore.jks from secret
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > application/android/app/keystore.jks

      - name: üóÇÔ∏è Create key.properties file
        run: |
          cat <<EOF > application/android/key.properties
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_ALIAS_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_ALIAS }}
          storeFile=keystore.jks
          EOF

      - name: "üèó Build Signed APK with Flavor: ${{ matrix.flavor }}"
        run: |
          cd application
          flutter build apk --obfuscate --split-debug-info=out/android --flavor ${{ matrix.flavor }} -t lib/main_${{ matrix.flavor }}.dart

      - name: üì¶ Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.flavor }}-release-apk
          path: application/build/app/outputs/apk/${{ matrix.flavor }}/release/app-${{ matrix.flavor }}-release.apk
